version: '3.4'

services:
  clamav-server:
    image: quay.io/ukhomeofficedigital/clamav
    ports:
      - "3310:3310"
  webapp:
    image: intakecontainerregistry.azurecr.io/intake-service:1.0.2
    ports:
      - "80:8080"
